### ISSUE TITLE
[Bug] Not copying directories containing spaces

### ISSUE THREAD

**Issue by TheXRMonk** [andstor/copycat-action#40] opened 2020-05-01 13:33 UTC
As title says. 
Also, I tried to use exclude to avoid copying .github/workflows/ but that also doesn't seem to work.

Otherwise this is an awesome action!

**Comment by andstor** [comment] 2020-05-06 13:06
Hi! Glad you like the action ☺️
Unfortunately i am very bussy at the moment, so I will come back to you in a couple of weeks or so. 

If you want, please open a pull request fixing the bug. Contributions are much appreciated!

**Comment by yceballost** [comment] 2020-06-08 20:26
interested in this issue

**Comment by andstor** [comment] 2020-06-09 21:46
Sorry for the delay, I have been extremely busy 😅 However, I hope to be able to fix this bug shortly!

It seems that the problem is that some of the variables regarding path names are not double quoted. This results in directories (and maybe files) with spaces to not be copied over. Adding double quotations around these variables should resolve the issue.

**Comment by yceballost** [comment] 2020-06-10 12:26
#42 I did a pull request to solve the problem

**Comment by andstor** [comment] 2020-06-13 12:20
> #42 I did a pull request to solve the problem

Great 👌

The pull request is now merged, and a new release [v3.2.2](https://github.com/andstor/copycat-action/releases/tag/v3.2.2) is published.

**Closed as completed by andstor** 2020-06-13 12:20 UTC
